scheme: Pisces
darkmode: true
menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  about: /about/ || fa fa-user
  博客园: https://www.cnblogs.com/undefined || fa fa-external-link-alt
social:
  GitHub: https://github.com/little-daimi || fab fa-github
  博客园: https://www.cnblogs.com/undefined || fa fa-pen
social_icons:
  enable: true
  icons_only: false
sidebar:
  position: left
  display: always
  padding: 18
  offset: 12
toc:
  enable: true
  number: true
  wrap: true
codeblock:
  theme:
    light: default
    dark: stackoverflow-dark
  copy_button:
    enable: true
    show_result: true
back2top:
  enable: true
  sidebar: false
  scrollpercent: true
local_search:
  enable: true
  top_n_per_article: 3
  unescape: false
  preload: false
rss: /atom.xml
font:
  enable: false
motion:
  enable: false
footer:
  since: 2025
