title: undefined
subtitle: u / n — d _
description: imiab 的个人博客，记录 CTF、Pwn、逆向分析与开发。
author: imiab
language: zh-CN
timezone: Asia/Shanghai
url: https://imi-imiab.com
root: /
permalink: posts/:title/
pretty_urls:
  trailing_index: false
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
new_post_name: :title.md
default_layout: post
post_asset_folder: false
render_drafts: false
future: false
updated_option: date
external_link:
  enable: true
  field: site
  exclude: []
syntax_highlighter: highlight.js
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: '    '
index_generator:
  path: ''
  per_page: 8
  order_by: -date
per_page: 20
pagination_dir: page
date_format: YYYY-MM-DD
time_format: HH:mm
theme: noise
feed:
  type: atom
  path: atom.xml
  limit: 20
sitemap:
  path: sitemap.xml
